'use client';

import { useState } from 'react';
import { Sparkles, ChevronDown } from 'lucide-react';
import { useTranslation } from '@/lib/i18n';

interface ArticleTldrProps {
  summary: string;
  summaryEn?: string;
}

/**
 * TLDR summary box shown at the top of an article when an AI summary exists.
 * Collapsible, bilingual (AR primary, EN secondary).
 */
export default function ArticleTldr({ summary, summaryEn }: ArticleTldrProps) {
  const { locale } = useTranslation();
  const [expanded, setExpanded] = useState(true);
  const [showEn, setShowEn] = useState(false);

  const displaySummary = showEn && summaryEn ? summaryEn : summary;

  return (
    <div className="rounded-2xl border border-gold/20 bg-gold/5 overflow-hidden mb-6">
      {/* Header */}
      <button
        onClick={() => setExpanded((v) => !v)}
        className="w-full flex items-center justify-between px-5 py-3.5 text-start"
      >
        <div className="flex items-center gap-2 text-gold">
          <Sparkles size={15} />
          <span className="text-sm font-[family-name:var(--font-display)] font-semibold">
            {locale === 'ar' ? 'الملخص الذكي' : 'AI Summary'}
          </span>
        </div>
        <ChevronDown
          size={16}
          className={`text-gold/60 transition-transform duration-200 ${expanded ? 'rotate-180' : ''}`}
        />
      </button>

      {/* Body */}
      {expanded && (
        <div className="px-5 pb-5">
          <p
            className="text-ink/85 text-[15px] leading-relaxed font-[family-name:var(--font-display)] text-start"
            dir="rtl"
          >
            {displaySummary}
          </p>

          {/* Language toggle */}
          {summaryEn && (
            <button
              onClick={() => setShowEn((v) => !v)}
              className="mt-3 text-xs text-gold/60 hover:text-gold transition-colors font-[family-name:var(--font-display)]"
            >
              {showEn ? 'عرض النسخة العربية' : 'View in English'}
            </button>
          )}

          <p className="mt-3 text-[11px] text-ink/40 font-[family-name:var(--font-display)] text-start" dir="rtl">
            {locale === 'ar' ? 'تم توليد هذا الملخص بواسطة الذكاء الاصطناعي' : 'Generated by AI · May not reflect all nuances'}
          </p>
        </div>
      )}
    </div>
  );
}
